import streamlit as st
from streamlit_option_menu import option_menu

def emo():
    selected = option_menu(
        menu_title=None,
        options=['joy', 'anger','sadness','surprise','fear','shame','disgust'],
        orientation='horizontal',
        icons=[':smile:',':angry',':cry:',':smile:',':angry',':cry:','none']
    )

    if selected=='joy':
        st.header("joy :smile:")
        st.write("""In a world often draped in shadows and uncertainties, joy emerges as a radiant beam of light, painting the canvas of life with vibrant hues of warmth and exuberance. It is an emotion that transcends the boundaries of the ordinary, transforming the mundane into moments of sheer magic and unbridled delight. Joy is the symphony that plays in the heart when laughter dances freely, and the spirit becomes an effervescent melody.

At its core, joy is a complex and multifaceted emotion, an elixir that bubbles up from the wellsprings of the soul, infusing every fiber of our being with an electrifying energy. It manifests in myriad forms, from the quiet contentment that settles like a gentle breeze to the unrestrained ecstasy that sends ripples of euphoria through our very existence.

Picture a sunlit meadow adorned with a carpet of wildflowers swaying in the soft embrace of a summer breeze. The air is infused with the sweet scent of blossoms, and the sunlight casts a golden glow, awakening a sense of joy that resonates with the vibrant tapestry of nature. Joy, in this moment, is the sunlight that kisses the skin and the harmonious chorus of rustling leaves.

Joy is the infectious laughter of children, echoing through the corridors of time, a pure and untainted expression that knows no boundaries. It's the gleeful abandon with which they chase butterflies in a field or the unbridled curiosity that lights up their eyes like constellations in the night sky. In their laughter, joy becomes a tangible force, a reminder of the beauty found in the simplest of moments.

As the pages of life turn, joy often reveals itself in connections forged between kindred spirits. It's the warmth of an embrace shared between friends who have weathered the storms of life together. The laughter that reverberates in a shared joke or the quiet understanding that needs no words – these are the threads that weave the fabric of joy in the tapestry of relationships.

Joy is also the artist's brushstroke on the canvas of creativity. It's the musician lost in the rhythm of a melody, the writer immersed in the flow of words, and the dancer swept away by the cadence of movement. In these moments of creative immersion, joy is the muse that guides the hands and hearts of creators, turning expression into a celebration of the human experience.

The aroma of a home-cooked meal wafting through the kitchen, the sizzle of ingredients in a pan, and the anticipation of a shared feast – joy, too, finds its expression in the simple act of nourishing both body and soul. It's the comfort found in the familiar flavors of a favorite dish and the joyous communion around a table where stories are shared as freely as the food.

Yet, joy is not immune to the ebb and flow of life. It coexists with its counterparts – sorrow, pain, and challenges. In fact, it is often in the face of adversity that joy shines its brightest. It becomes the resilient ember that glows in the darkest nights, a testament to the indomitable spirit of the human heart. The triumph over obstacles, the resilience in the face of setbacks – these are the chapters where joy, though tested, emerges triumphant.

Consider the joy that emanates from acts of kindness and altruism. It's the warmth that spreads through the giver and receiver alike when a helping hand is extended without expectation. Joy, in these moments, transcends the individual, becoming a collective force that ripples through communities, fostering a sense of interconnectedness and shared humanity.

In the grand tapestry of life, joy is the thread that weaves together the moments of bliss, the threads of connection, and the resilience that propels us forward. It is both a destination and a journey, a destination that we often seek and a journey that unfolds in the everyday moments, in the laughter shared, the kindness extended, and the beauty discovered in the world and within ourselves.

Ultimately, joy is a celebration of life in all its facets – the highs and lows, the victories and defeats. It's a melody that plays in the heart, a dance that unfolds in the soul, and a radiant light that brightens the path we tread. In the pursuit of joy, we discover not only the capacity for happiness but also the resilience to navigate the complexities of the human experience with grace and gratitude.""")
    if selected=='anger':
        st.header("anger :angry:")
        st.write("""Anger, a tempest that brews within the human spirit, is a primal force that courses through the veins, altering the landscape of emotions with its fiery intensity. It is a visceral reaction to perceived injustices, unmet expectations, or a collision between reality and one's desires. In the vast spectrum of human emotions, anger stands as a complex and potent force, capable of both destructive eruptions and transformative power.

At its core, anger is an ancient sentinel, a survival mechanism deeply embedded in the human psyche. It emerges as a response to threats, whether real or imagined, signaling a readiness to defend and assert boundaries. In its purest form, anger is a messenger, a beacon that calls attention to perceived violations, urging the individual to confront challenges head-on.

The genesis of anger lies in the intricate dance of cognition and emotion. It arises when expectations collide with reality, birthing a dissonance that reverberates through the psyche. It may stem from personal slights, thwarted ambitions, or a sense of powerlessness, each ember adding fuel to the simmering furnace within.

Imagine a scene where frustration morphs into anger, where the tightrope of tolerance teeters perilously close to the edge. It might manifest as a quickened pulse, a flush of heat that climbs the cheeks, or the clenching of fists as the body readies itself for action. In this heightened state, reason often takes a backseat, and the raw, unbridled energy of anger surges forth, demanding acknowledgment and release.

The expression of anger varies widely among individuals, ranging from explosive outbursts to silent seething. The volcanic eruption, characterized by raised voices and animated gestures, releases the pent-up energy in a torrent of words and actions. Alternatively, the silent simmering of anger may manifest as a cold, searing gaze, a deliberate withdrawal, or the palpable tension that hangs in the air like an impending storm.

Yet, anger is a double-edged sword, capable of both destruction and revelation. Unchecked, it can unleash a torrent of chaos, damaging relationships and leaving scorched earth in its wake. However, harnessed and channeled constructively, anger becomes a catalyst for change, a transformative force that fuels assertiveness, sets boundaries, and propels individuals toward necessary action.

In intimate relationships, anger acts as a crucible where emotions are tested and truths are laid bare. It becomes the crucible in which conflicts are distilled, revealing the core issues that demand attention. The ability to navigate anger within the context of relationships requires emotional intelligence, empathy, and a willingness to engage in open dialogue.

The aftermath of anger is often a landscape marked by the debris of shattered expectations and the remnants of unspoken words. Guilt may linger in the air, a poignant reminder of the impact that anger can have on oneself and others. The challenge lies in the aftermath – the delicate process of reconciliation, forgiveness, and the rebuilding of bridges that anger may have scorched.

In the workplace, anger assumes a different guise, often entwined with the complexities of power dynamics and professional hierarchies. It may be the frustration of unmet deadlines, the indignation at perceived injustices, or the clash of differing perspectives. Effectively managing workplace anger requires a delicate balance between assertiveness and professionalism, as well as strategies for conflict resolution.

Psychologically, the impact of chronic, unaddressed anger can be profound. It may fester, giving rise to a simmering resentment that colors one's worldview. The long-term consequences may manifest as physical ailments, mental health issues, or a pervasive sense of discontent. Recognizing the signs of maladaptive anger and seeking appropriate outlets for its expression becomes crucial for emotional well-being.

Therapeutically, addressing anger often involves exploring its roots, understanding the underlying triggers, and developing coping mechanisms. Cognitive-behavioral therapies offer tools for identifying and challenging distorted thought patterns associated with anger, promoting healthier responses to provocations. Mindfulness practices, such as meditation and deep-breathing exercises, provide avenues for cultivating self-awareness and emotional regulation.

Anger, as a universal emotion, finds its place in art, literature, and cultural expressions. It becomes the subject of paintings that capture the tumultuous swirl of emotions, the protagonist in narratives that explore the human condition, and the inspiration for music that channels the raw energy of the emotion. In this way, anger transcends the individual experience, resonating across the collective consciousness of humanity.

In the grand tapestry of emotions, anger stands as a vibrant thread, woven into the fabric of the human experience. It is an emotion that demands acknowledgment, understanding, and channeling toward constructive ends. Whether it manifests as a brief spark or a sustained flame, anger remains an integral part of the human emotional repertoire, a potent force that shapes the contours of our relationships, our personal growth, and the very essence of our humanity.""")
    if selected=='sadness':
        st.header("sadness :cry:")
        st.write("""Sadness, a poignant and universal emotion, weaves its way through the tapestry of the human experience, casting shadows on the canvas of our lives. It is a profound and complex emotion, one that transcends cultural, linguistic, and geographical boundaries, leaving an indelible mark on the soul. As a nuanced response to loss, disappointment, or the ephemeral nature of existence, sadness resonates as a reminder of our shared vulnerability and the depth of our capacity to feel.

At its essence, sadness is an emotional state characterized by a deep and often melancholic sorrow. It manifests as a heaviness in the heart, a weight that settles in the chest and colors the world in muted tones. Unlike fleeting moods, sadness is an enduring companion, lingering like a gentle rain that drizzles over the landscape of the soul, gradually seeping into the cracks of our being.

Consider the scene of a rainy day, where the skies weep in tandem with the tears of the earth. The pitter-patter of raindrops becomes a melancholy melody, echoing the cadence of a somber heart. In this atmospheric interplay, nature mirrors the emotional landscape of sadness, creating a symphony of muted hues and a quiet introspection.

The visage of sadness varies from person to person, revealing itself through a myriad of subtle expressions. It might be the downturned corners of the mouth, the furrowed brows that trace the contours of internal turmoil, or the far-off gaze that hints at a mind lost in the recesses of poignant memories. The body, too, becomes a canvas, mirroring the emotional landscape within – shoulders slumped, steps measured, and gestures softened by the weight of introspection.

Sadness often arises as a response to loss – the loss of a loved one, the dissolution of a relationship, or the shattering of dreams. It is an emotion intricately entwined with the ebb and flow of life's inevitable transitions. The death of a loved one becomes a poignant symphony of grief, where each note played is tinged with the ache of absence, and memories become bittersweet echoes.

In the realm of romantic relationships, sadness may be the silent witness to the unraveling of connections once thought unbreakable. The end of a love story, whether marked by a gradual drift or the abrupt severance of ties, casts a long shadow of sorrow. In the echoes of shared laughter and whispered promises, sadness lingers as a testament to the fragility of human connections.

Yet, sadness is not confined to grand narratives of loss. It may emerge in the mundane, in the quiet moments when the weight of the world settles on weary shoulders. It might be the result of unfulfilled expectations, the recognition of personal limitations, or the acknowledgment of the impermanence inherent in all things. In these understated instances, sadness becomes an intimate companion, a mirror reflecting the vulnerabilities that define our shared humanity.

The experience of sadness extends beyond the individual, shaping the dynamics of relationships and communities. It becomes the common thread that binds us, fostering empathy and shared understanding. In communal sorrow, whether in response to natural disasters, collective traumas, or societal injustices, sadness becomes a unifying force that transcends individual differences, reminding us of our interconnectedness.

Navigating sadness requires an intimate dance with introspection and self-compassion. It beckons us to explore the recesses of our emotions, to sit with the discomfort, and to acknowledge the validity of our feelings. The pursuit of happiness often casts a long shadow, for it is in embracing sadness that we cultivate emotional resilience and authenticity.

The expression of sadness, both in solitude and within the context of relationships, is a delicate art. It may find its voice in the solitude of a tear-streaked journal, the catharsis of creative expression, or the solace sought in the presence of compassionate companions. Conversely, the shared experience of sadness within relationships hinges on a delicate dance of vulnerability and support, as loved ones extend a listening ear or a comforting embrace.

Therapeutically, sadness is explored in the safe confines of counseling sessions, where the intricacies of grief and loss are tenderly unravelled. Psychotherapeutic modalities, such as cognitive-behavioral therapy (CBT) and grief counseling, offer tools for understanding and navigating the complexities of sadness. Mindfulness practices, with their focus on being present with one's emotions without judgment, provide a pathway for acknowledging and embracing sadness with compassion.

In literature and the arts, sadness becomes the muse for poets, writers, and artists who seek to capture the ineffable beauty within the spectrum of human emotions. It inspires the haunting melodies of musicians, the evocative brushstrokes of painters, and the poignant prose of novelists. In the creative expression of sadness, the raw authenticity of the human experience is laid bare for contemplation and connection.

The aftermath of sadness is a landscape marked by the tender shoots of resilience and the potential for growth. It is a transformative journey that, when navigated with introspection and self-care, leads to a deeper understanding of oneself and the world. The scars left by sadness become testaments to the strength that arises from vulnerability, and the process of healing becomes an affirmation of the human spirit's capacity to endure and transcend.

In the grand tapestry of emotions, sadness stands as a testament to the depth and breadth of the human experience. It is the undercurrent that adds richness to the symphony of life, a poignant melody that resonates through the corridors of time. Acknowledging and embracing sadness, with its muted hues and gentle melancholy, becomes an integral part of the journey toward authenticity, empathy, and the profound interconnectedness that binds us all.""")
    if selected=='surprise':
        st.header("surprise :astonished:")
        st.write("""Surprise, a fleeting and electrifying emotion, serves as the spark that ignites the human experience, infusing it with a jolt of unexpected energy. It is the exhilarating twist in the narrative of life, an emotional crescendo that unfolds in response to unforeseen events, challenging our expectations and momentarily suspending the ordinary. Surprise, with its multifaceted nature, embodies joy, curiosity, and a touch of vulnerability, inviting us to embrace the unpredictability that defines the human journey.

At its core, surprise is an emotional state triggered by the sudden and unanticipated. It is the proverbial curveball that life throws our way, momentarily diverting us from the familiar path and prompting a recalibration of our perceptions. Picture a scene where the curtain of predictability is lifted, revealing a tableau of the unexpected. It might be the sudden appearance of an old friend, an unexpected accolade, or a serendipitous turn of events that defies the ordinary. In these moments, surprise acts as a catalyst, injecting a burst of novelty into the routine of everyday life.

The physiological response to surprise is a symphony of reactions orchestrated by the autonomic nervous system. The widened eyes, the sharp intake of breath, and the raised eyebrows are all telltale signs of the body's instinctive reaction to the unexpected. This visceral response, often accompanied by a quickening heartbeat, reflects the innate readiness to confront the unknown, whether it brings joyous revelations or challenges to be navigated.

Surprise wears many faces, each revealing a facet of its dynamic nature. It may manifest as the joyous exuberance of a surprise party, where laughter and shared moments of revelry punctuate the atmosphere. Alternatively, surprise may emerge as a quiet, introspective awe, a hushed acknowledgment of the beauty found in unexpected encounters with the sublime. It is the discovery of a hidden talent, the unexpected kindness of a stranger, or the unveiling of a breathtaking sunset that leaves us momentarily breathless.

The emotional resonance of surprise extends beyond individual experiences, permeating the fabric of human connections and relationships. In the context of personal interactions, surprise becomes the currency of shared joy, the secret ingredient that strengthens the bonds between individuals. Whether it's a thoughtful gesture, an unforeseen reunion, or an unexpected revelation, surprise becomes the glue that binds people together, creating shared memories and deepening the tapestry of human connections.

Consider the surprise inherent in the unveiling of artistic masterpieces, the unexpected plot twists in literature, or the ingenious inventions that redefine the course of history. Surprise, in these creative expressions, becomes a catalyst for innovation, pushing the boundaries of what is known and familiar. It is the element of unpredictability that fuels the engines of creativity, inviting artists, writers, and inventors to explore uncharted territories and challenge the status quo.

In the realm of science, surprise is the driving force behind the pursuit of discovery. It is the unexpected findings that challenge existing theories, paving the way for paradigm shifts and scientific revolutions. The serendipitous moments, the "Eureka!" instances, and the unforeseen connections become the hallmarks of scientific progress, reminding us that curiosity and surprise are the guiding lights in the quest for knowledge.

Navigating surprise requires a delicate dance between openness and adaptability. It demands a willingness to embrace the unknown, to release the grip on preconceived notions, and to welcome the unfolding of possibilities. The capacity to navigate surprise with resilience and curiosity transforms it from a momentary disruption into an opportunity for growth and learning. The ability to find delight in the unexpected is a skill that enhances our emotional agility and enriches our experience of the world.

Therapeutically, surprise serves as a powerful tool for breaking through patterns of thought and behavior. In therapeutic interventions, counselors and psychologists often employ surprise elements to disrupt ingrained habits, challenge limiting beliefs, and stimulate new perspectives. The unexpected insights gained through these experiences become catalysts for personal transformation, inviting individuals to explore alternative narratives and possibilities.

Surprise is also intricately linked to the concept of wonder, that childlike curiosity that propels us to question, explore, and marvel at the world around us. In the gaze of a child encountering a butterfly for the first time or in the fascination inspired by the cosmos, surprise becomes a conduit for reconnecting with the innate sense of awe that resides within each of us.

The aftermath of surprise is marked by a cascade of emotions that may include joy, curiosity, and, at times, a touch of vulnerability. It leaves an indelible imprint on memory, becoming a milestone in the narrative of our lives. The stories we tell, the anecdotes we share, and the moments we cherish often revolve around the unexpected, the twists that turned ordinary days into extraordinary chapters.

In literature and the arts, surprise is the storyteller's ally, the narrative device that captivates audiences and keeps them on the edge of their seats. It is the unexpected plot twist that transforms a good story into a memorable one, leaving readers or viewers with a sense of wonder and a desire to unravel the mysteries that lie ahead.

In conclusion, surprise is a dynamic and exhilarating emotion that injects vitality into the fabric of human existence. It is the bridge between the known and the unknown, the catalyst for joy and curiosity, and the spark that kindles the flames of creativity and innovation. Embracing surprise with an open heart and a curious mind allows us to navigate the unpredictable nature of life with grace, transforming the ordinary into the extraordinary and infusing our journey with the magic of the unexpected.""")
    if selected=='fear':
        st.header("fear :fearful::scream:")
        st.write("""Fear, a primal and ancient emotion woven into the fabric of human existence, is a visceral response to perceived threats, real or imagined. It is a sentinel that has accompanied humanity throughout its evolutionary journey, an adaptive mechanism finely tuned to alert us to danger and propel us into action. As a complex and multifaceted emotion, fear manifests in various forms, from the immediate, heart-pounding response to imminent peril to the more subtle, lingering anxieties that shape our daily lives. In exploring the depths of fear, we uncover a spectrum of emotions that range from primal survival instincts to the intricate nuances of phobias, anxieties, and existential fears.

At its core, fear is an acute response to stimuli that trigger the body's fight-or-flight mechanism. Imagine a scene where the crackling of twigs in the dark or the sudden appearance of a predator elicits an immediate surge of adrenaline, sharpening the senses and preparing the body to confront or evade the perceived threat. This primal response, deeply embedded in our evolutionary history, underscores fear as a survival mechanism designed to enhance our chances of navigating hazardous situations.

The physiological manifestations of fear are a symphony of responses orchestrated by the autonomic nervous system. Rapid heartbeat, shallow breathing, dilated pupils, and heightened alertness are the body's instinctive reactions, preparing us for rapid action. This acute physiological response is finely tuned to mobilize energy and focus, enabling us to confront threats head-on or flee from imminent danger.

Fear, however, is not limited to immediate physical threats. It permeates the intricate landscape of our minds, giving rise to a myriad of emotional and psychological nuances. It may manifest as anxiety, a diffuse and persistent unease that lacks a specific threat yet casts a shadow over daily life. The fear of the unknown, the fear of failure, or the fear of rejection are examples of these more nuanced expressions, each weaving its own narrative within the tapestry of human experience.

Consider the fear of public speaking, a phenomenon known as glossophobia, which can induce a level of anxiety comparable to facing physical danger. The anticipation of judgment, the fear of making mistakes, and the vulnerability of being in the spotlight converge to evoke a potent emotional response. In this context, fear transcends the immediate physical realm and extends into the complex interplay of social dynamics and personal insecurities.

Phobias, characterized by intense and irrational fears of specific objects or situations, exemplify fear's ability to manifest in seemingly innocuous contexts. Whether it's the fear of heights (acrophobia), the fear of spiders (arachnophobia), or the fear of flying (aviophobia), phobias create a disproportionate emotional response that can significantly impact an individual's daily life. The mere thought or encounter with the feared stimulus can trigger an overwhelming surge of fear, leading to avoidance behaviors and a persistent sense of unease.

Existential fears, rooted in the contemplation of life's impermanence and the uncertainty of the future, represent a more abstract and philosophical dimension of fear. The fear of death, the fear of meaninglessness, or the fear of the unknown can stir existential angst, prompting individuals to grapple with profound questions about the nature of existence. These fears, while intangible, have the power to shape belief systems, influence life choices, and foster a deep introspection into the meaning and purpose of life.

In the realm of storytelling, fear becomes a potent narrative device that captivates and resonates with audiences. Horror literature and films, for example, leverage the primal aspects of fear to elicit a visceral response. The anticipation, suspense, and the sudden revelation of the unknown tap into our collective fears, creating an immersive experience that explores the boundaries of human vulnerability.

Overcoming fear, whether it's the immediate response to a threat or the more subtle anxieties that permeate daily life, is a transformative journey that requires courage and resilience. Therapeutically, addressing fear often involves cognitive-behavioral interventions, exposure therapy, and mindfulness practices aimed at restructuring thought patterns, desensitizing irrational fears, and fostering a sense of calm in the face of anxiety.

The aftermath of fear varies widely, leaving imprints that range from traumatic scars to personal growth. Traumatic experiences may imprint indelible memories, leading to post-traumatic stress disorder (PTSD) and a heightened sensitivity to potential threats. On the other hand, overcoming fears through gradual exposure and therapeutic interventions can lead to empowerment, resilience, and a newfound sense of agency.

In conclusion, fear is a complex and integral facet of the human experience, rooted in our evolutionary history and intricately entwined with our psychological and emotional landscapes. It is a dynamic force that can propel us into action, heighten our awareness, or, if left unchecked, manifest as anxiety and phobias that shape our perceptions of the world. Acknowledging and understanding fear, with its primal instincts and nuanced expressions, allows us to navigate the intricate interplay of survival instincts, social dynamics, and existential contemplation that define the human condition. Embracing fear as a transformative force enables us to cultivate resilience, confront challenges, and embark on a journey of self-discovery that transcends the boundaries of our comfort zones.""")
    if selected=='shame':
        st.header("shame :disappointed:")
        st.write("""Shame, a complex and profound emotion, casts a shadow on the human psyche, intertwining with the threads of self-perception, social dynamics, and personal morality. It is an intimate and often painful experience, arising from a perceived failure to meet societal or internalized standards. As one of the self-conscious emotions, shame goes beyond momentary embarrassment, delving into the depths of self-worth, identity, and the intricate dance of societal expectations. In exploring the contours of shame, we encounter the delicate interplay between cultural influences, individual vulnerabilities, and the transformative potential that arises from navigating this deeply human emotion.

At its core, shame is a self-evaluative emotion, rooted in the awareness of one's perceived shortcomings or violations of social norms. Picture a scene where the eyes of others, or even the internalized gaze of oneself, converge on a perceived transgression. It might be a public mistake, a breach of moral standards, or a deviation from personal ideals. In these moments, shame emerges as a visceral response, a tightening in the chest, a flushed face, or a desire to retreat from the gaze of others.

The genesis of shame lies in the intricate tapestry of cultural and societal expectations. It is shaped by the values, norms, and moral codes that define a community, and it serves as a powerful social regulator. The fear of being ostracized, rejected, or deemed unworthy by others contributes to the pervasive nature of shame. It becomes a silent arbiter of acceptability, urging individuals to conform to established norms and reinforcing the boundaries of societal expectations.

Shame is not a monolithic emotion; rather, it exists on a spectrum that ranges from healthy, adaptive shame to toxic, paralyzing shame. Healthy shame serves as a moral compass, guiding individuals toward a recognition of their mistakes and fostering personal growth. It becomes a catalyst for learning, empathy, and accountability. However, when shame becomes toxic, it transforms into a corrosive force that erodes self-esteem, stifles authenticity, and perpetuates cycles of self-blame.

The interplay between shame and identity is a nuanced exploration of self-perception and societal judgment. Shame has the power to shape one's narrative, influencing the stories individuals tell themselves about their worthiness, belonging, and inherent value. The internalized shame associated with stigmatized identities, such as those related to race, gender, or sexuality, adds layers of complexity to the already intricate tapestry of self-identity.

Consider the shame experienced by individuals grappling with mental health challenges. The stigma attached to mental health issues often contributes to a sense of inadequacy and internalized shame, leading individuals to hide their struggles and avoid seeking support. This intersection of mental health and shame highlights the profound impact societal attitudes can have on individual well-being.

The role of shame in interpersonal relationships is a delicate dance of vulnerability and connection. Shame has the power to strain relationships, as individuals may withdraw, become defensive, or resort to maladaptive coping mechanisms to mask their perceived flaws. On the other hand, the acknowledgment and sharing of shame within the context of supportive relationships can foster intimacy, empathy, and a deeper understanding of shared vulnerabilities.

Parental influences play a pivotal role in the development of shame, as caregivers become the primary agents of socialization. The messages conveyed during childhood about one's worth, acceptability, and lovability contribute to the formation of core beliefs that shape the individual's relationship with shame. A parenting style that emphasizes unconditional love, empathy, and a safe space for mistakes can buffer against the corrosive effects of toxic shame.

Therapeutically, addressing shame involves a delicate exploration of its origins, manifestations, and impact on an individual's life. Therapists often employ modalities such as psychodynamic therapy, cognitive-behavioral therapy (CBT), and dialectical behavior therapy (DBT) to unravel the layers of shame, challenge maladaptive beliefs, and foster self-compassion. Group therapy and support communities provide a communal space where individuals can share their experiences of shame, breaking the isolation that often accompanies this emotion.

The aftermath of shame can be profound, shaping the trajectory of an individual's life in myriad ways. Shame may lead to a persistent sense of unworthiness, self-sabotage, or the adoption of perfectionistic tendencies as a coping mechanism. Alternatively, the transformative potential of shame lies in the opportunity for growth, self-reflection, and the development of resilience. Navigating shame with courage and self-compassion allows individuals to rewrite the narrative, embracing their imperfections and reclaiming a sense of agency in shaping their self-worth.

In literature, art, and cultural expressions, shame becomes a powerful theme that resonates across diverse narratives. Characters grappling with shame, redemption, and the pursuit of self-acceptance populate the pages of literature, the frames of paintings, and the stages of theatrical performances. These creative explorations reflect the universality of shame as a theme that transcends individual experiences, resonating with audiences on a deeply emotional level.

The cultural dimensions of shame reveal the intricate dance between societal expectations and individual identity. Different cultures may have varying attitudes toward shame, influencing how individuals navigate their experiences of self-evaluation and acceptance. The collective nature of shame within cultural contexts underscores the importance of fostering cultures of compassion, empathy, and acceptance.

In conclusion, shame is a complex and pervasive emotion that weaves through the tapestry of human experience. It is a nuanced exploration of self-worth, societal expectations, and the transformative potential that arises from navigating the depths of this emotion. Acknowledging and understanding shame, with its multifaceted manifestations and profound impact, invites individuals to embark on a journey of self-discovery, self-compassion, and the cultivation of resilience. Embracing the vulnerabilities inherent in the human experience allows for the rewriting of narratives, breaking free from the shackles of toxic shame, and fostering a more authentic connection with oneself and others.""")
    
    if selected=='disgust':
        st.header("disgust :face_vomiting:")
        st.write("""A visceral and powerful emotion, disgust emerges as a primal response to stimuli perceived as offensive, repulsive, or contaminating. It is a complex and adaptive mechanism deeply ingrained in the human psyche, serving as a protective barrier against potential threats to physical and social well-being. The experience of disgust extends beyond mere distaste; it encompasses a spectrum of responses that range from the rejection of foul odors to the aversion to moral transgressions. In exploring the contours of disgust, we delve into the intricate interplay of evolutionary instincts, cultural influences, and the psychological nuances that shape this intricate emotion.

At its essence, disgust is a survival mechanism designed to protect the individual from harm. Consider the immediate recoil from spoiled food, the instinctual aversion to bodily fluids, or the revulsion at the sight of potential contaminants. These reactions, rooted in evolutionary history, serve as a first line of defense against the ingestion of harmful substances or the exposure to pathogens. Disgust is, therefore, an adaptive response that aids in the avoidance of potential dangers, contributing to the preservation of individual health and well-being.

The physiological manifestations of disgust are readily apparent, involving a range of responses designed to expel or distance oneself from the source of aversion. These may include facial expressions such as nose wrinkling, lip curling, and averted gaze. The sensation of nausea, accompanied by a queasy stomach and a desire to physically distance oneself from the offensive stimulus, further underscores the bodily nature of the disgust response.

The spectrum of disgust extends beyond its primary role in safeguarding physical health to encompass social and moral dimensions. The social aspect of disgust involves reactions to behaviors or individuals perceived as socially undesirable or morally reprehensible. The revulsion directed towards actions such as lying, cheating, or violating societal norms reflects the intricate interplay between disgust and moral judgment. In this context, disgust becomes a tool for enforcing social norms and maintaining the integrity of interpersonal relationships.

Cultural influences play a significant role in shaping the landscape of disgust, as societal norms dictate what is considered acceptable or repugnant within a given community. Food taboos, for instance, vary widely across cultures, with certain dishes or dietary practices eliciting disgust in some societies while being embraced in others. The malleability of disgust in response to cultural norms highlights its dynamic nature and underscores its role as a social construct.

The psychological dimensions of disgust delve into the nuances of individual differences in tolerance and sensitivity. Research suggests that individuals vary in their dispositional levels of disgust sensitivity, with some people exhibiting heightened reactions to potential contaminants or morally objectionable stimuli. These individual differences may be influenced by genetic factors, early childhood experiences, or cultural upbringing, shaping the way individuals navigate their emotional responses to the world around them.

Phobias and obsessive-compulsive disorders may amplify the experience of disgust, leading individuals to engage in ritualistic behaviors aimed at avoiding perceived contaminants or preventing the spread of contamination. These clinical manifestations highlight the potential for disgust to become maladaptive, interfering with daily functioning and contributing to heightened levels of anxiety.

The intersection of disgust with other emotions, such as fear or anger, further enriches its complexity. In situations where disgust coexists with fear, the emotional response may be characterized by a heightened sense of aversion and the desire to escape the source of threat. Conversely, when disgust intertwines with anger, it may fuel a more confrontational response, as seen in reactions to perceived moral transgressions.

In the realm of interpersonal relationships, the expression of disgust becomes a nuanced dance of boundaries and empathy. Couples navigating the intricacies of intimacy, for example, may negotiate the balance between personal preferences and mutual respect for individual sensitivities to disgust. The ability to communicate openly about preferences and sensitivities fosters understanding and strengthens the emotional connection between individuals.

Therapeutically, addressing disgust involves exploring the origins of aversions, whether they are related to specific stimuli, past traumas, or cultural influences. Exposure therapy, a therapeutic approach that gradually introduces individuals to the source of aversion in a controlled and supportive environment, can be effective in desensitizing disgust responses. Cognitive-behavioral therapy (CBT) may also be employed to challenge and reframe maladaptive thought patterns associated with disgust.

The aftermath of disgust varies, leaving imprints that range from momentary discomfort to lasting behavioral changes. In situations where disgust is appropriately directed towards potential contaminants, the aftermath may involve avoidance behaviors or the adoption of hygiene practices to mitigate future risks. However, when disgust becomes entangled with maladaptive patterns, the aftermath may manifest as heightened anxiety, impaired social functioning, or persistent distress.

Literary and artistic expressions often leverage the emotional power of disgust to evoke visceral reactions from audiences. Horror literature and films, for example, utilize elements of disgust to elicit fear and repulsion, playing on the primal aspects of human psychology. Visual artists, too, explore the boundaries of disgust as a theme, challenging societal norms and prompting viewers to confront their own visceral reactions.

In conclusion, disgust is a multifaceted and adaptive emotion that traverses the realms of physical health, social dynamics, and moral judgment. Its evolutionary roots as a protective mechanism underscore its role in safeguarding individual well-being. Yet, the social and cultural dimensions of disgust highlight its malleability and the influence of societal norms in shaping emotional responses. Navigating disgust involves a delicate dance between individual sensitivities, cultural influences, and the transformative potential that arises from understanding and recalibrating this intricate emotion. Embracing the nuances of disgust allows individuals to engage with the world with a heightened awareness of their emotional responses and the complexities that shape their perceptions of acceptability and repulsion.""")
